# fly.toml app configuration file generated for fitness-app-workout-api on 2025-05-15T14:38:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fitness-app-workout-api'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1